// PixelChat Nature Mega Pack v1 manifest.
// The PNG files are intentionally kept as standalone assets in public/nature-assets.
// This manifest centralizes their names, sizes, and categories for the Nature Test.
export const NATURE_ASSETS = {
  grassMicro01: { path: "/nature-assets/01_ground_grass/grass_micro_01.png", width: 16, height: 16 },
  grassMicro02: { path: "/nature-assets/01_ground_grass/grass_micro_02.png", width: 16, height: 16 },
  grassTuft01: { path: "/nature-assets/01_ground_grass/grass_tuft_01.png", width: 32, height: 32 },
  grassTuft02: { path: "/nature-assets/01_ground_grass/grass_tuft_02.png", width: 32, height: 32 },
  groundDetail01: { path: "/nature-assets/01_ground_grass/ground_detail_01.png", width: 16, height: 16 },
  groundDetail02: { path: "/nature-assets/01_ground_grass/ground_detail_02.png", width: 16, height: 16 },
  groundPatch01: { path: "/nature-assets/01_ground_grass/ground_patch_01.png", width: 64, height: 64 },
  groundPatch02: { path: "/nature-assets/01_ground_grass/ground_patch_02.png", width: 64, height: 64 },
  groundPatch03: { path: "/nature-assets/01_ground_grass/ground_patch_03.png", width: 64, height: 64 },
  mushroom01: { path: "/nature-assets/02_flowers_mushrooms/mushroom_01.png", width: 32, height: 32 },
  mushroom02: { path: "/nature-assets/02_flowers_mushrooms/mushroom_02.png", width: 32, height: 32 },
  mushroomCluster01: { path: "/nature-assets/02_flowers_mushrooms/mushroom_cluster_01.png", width: 64, height: 64 },
  tinyFlower01: { path: "/nature-assets/02_flowers_mushrooms/tiny_flower_01.png", width: 16, height: 16 },
  tinyFlower02: { path: "/nature-assets/02_flowers_mushrooms/tiny_flower_02.png", width: 16, height: 16 },
  wildFlower01: { path: "/nature-assets/02_flowers_mushrooms/wild_flower_01.png", width: 32, height: 32 },
  wildFlower02: { path: "/nature-assets/02_flowers_mushrooms/wild_flower_02.png", width: 32, height: 32 },
  wildFlower03: { path: "/nature-assets/02_flowers_mushrooms/wild_flower_03.png", width: 32, height: 32 },
  bush01: { path: "/nature-assets/03_plants_bushes/bush_01.png", width: 64, height: 64 },
  bush02: { path: "/nature-assets/03_plants_bushes/bush_02.png", width: 64, height: 64 },
  bush03: { path: "/nature-assets/03_plants_bushes/bush_03.png", width: 64, height: 64 },
  fern01: { path: "/nature-assets/03_plants_bushes/fern_01.png", width: 32, height: 32 },
  fern02: { path: "/nature-assets/03_plants_bushes/fern_02.png", width: 32, height: 32 },
  smallPlant01: { path: "/nature-assets/03_plants_bushes/small_plant_01.png", width: 32, height: 32 },
  smallPlant02: { path: "/nature-assets/03_plants_bushes/small_plant_02.png", width: 32, height: 32 },
  smallPlant03: { path: "/nature-assets/03_plants_bushes/small_plant_03.png", width: 32, height: 32 },
  pebble01: { path: "/nature-assets/04_rocks_stone/pebble_01.png", width: 16, height: 16 },
  pebble02: { path: "/nature-assets/04_rocks_stone/pebble_02.png", width: 16, height: 16 },
  rock01: { path: "/nature-assets/04_rocks_stone/rock_01.png", width: 32, height: 32 },
  rock02: { path: "/nature-assets/04_rocks_stone/rock_02.png", width: 64, height: 64 },
  rock03: { path: "/nature-assets/04_rocks_stone/rock_03.png", width: 64, height: 64 },
  rockCluster01: { path: "/nature-assets/04_rocks_stone/rock_cluster_01.png", width: 64, height: 64 },
  rockCluster02: { path: "/nature-assets/04_rocks_stone/rock_cluster_02.png", width: 64, height: 64 },
  branch01: { path: "/nature-assets/05_wood_forest_floor/branch_01.png", width: 16, height: 16 },
  branch02: { path: "/nature-assets/05_wood_forest_floor/branch_02.png", width: 32, height: 32 },
  fallenWoodCluster01: { path: "/nature-assets/05_wood_forest_floor/fallen_wood_cluster_01.png", width: 64, height: 64 },
  log01: { path: "/nature-assets/05_wood_forest_floor/log_01.png", width: 64, height: 64 },
  log02: { path: "/nature-assets/05_wood_forest_floor/log_02.png", width: 64, height: 64 },
  treeStump01: { path: "/nature-assets/05_wood_forest_floor/tree_stump_01.png", width: 64, height: 64 },
  treeLarge01: { path: "/nature-assets/06_trees/tree_large_01.png", width: 128, height: 128 },
  treeLarge02: { path: "/nature-assets/06_trees/tree_large_02.png", width: 128, height: 128 },
  treeMedium01: { path: "/nature-assets/06_trees/tree_medium_01.png", width: 128, height: 128 },
  treeMedium02: { path: "/nature-assets/06_trees/tree_medium_02.png", width: 128, height: 128 },
  treeSmall01: { path: "/nature-assets/06_trees/tree_small_01.png", width: 96, height: 96 },
  treeSmall02: { path: "/nature-assets/06_trees/tree_small_02.png", width: 96, height: 96 },
  pondEdgeCluster01: { path: "/nature-assets/07_water_shore/pond_edge_cluster_01.png", width: 64, height: 64 },
  reed01: { path: "/nature-assets/07_water_shore/reed_01.png", width: 32, height: 32 },
  shorelineDetail01: { path: "/nature-assets/07_water_shore/shoreline_detail_01.png", width: 64, height: 64 },
  shorelineDetail02: { path: "/nature-assets/07_water_shore/shoreline_detail_02.png", width: 64, height: 64 },
  waterPiece01: { path: "/nature-assets/07_water_shore/water_piece_01.png", width: 64, height: 64 },
  waterPiece02: { path: "/nature-assets/07_water_shore/water_piece_02.png", width: 64, height: 64 },
  waterPlant01: { path: "/nature-assets/07_water_shore/water_plant_01.png", width: 32, height: 32 },
} as const;

export type NatureAssetKey = keyof typeof NATURE_ASSETS;
